#!/bin/bash

# TODO Get mouse device automatically
# Workaround for now is to use evemu-record and evemu-describe

while true; do

  # Don't do anything if mouse is manually being moved.
  if (! sudo inotifywait /dev/input/event9 -qq -t 2); then

    sudo evemu-event /dev/input/event9 --type EV_REL --code REL_X --value 10 &&
      sudo evemu-event /dev/input/event9 --type EV_REL --code REL_Y --value 10 --sync

    sleep 2

    sudo evemu-event /dev/input/event9 --type EV_REL --code REL_X --value -10 &&
      sudo evemu-event /dev/input/event9 --type EV_REL --code REL_Y --value -10 --sync

  fi
done
